name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup pnpm
                uses: pnpm/action-setup@v2
                with:
                    version: latest
            -   name: Use Node.js LTS
                uses: actions/setup-node@v4
                with:
                    node-version: 'lts/*'
                    cache: 'pnpm'
            -   name: Install dependencies
                run: pnpm install
            -   name: Generate icons maskable
                run: pnpm icons-maskable
            -   name: Generate icons any
                run: pnpm icons-any
            -   name: Build Prod
                run: pnpm ng build --configuration production
            -   name: Archive build
                if: success()
                uses: actions/upload-artifact@v4
                with:
                    name: deploy_dist
                    path: dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Download build
                uses: actions/download-artifact@v4
                with:
                    name: deploy_dist
                    path: dist
            -   name: Find
                run: find
            -   name: Rsync to server
                uses: burnett01/rsync-deployments@v7
                with:
                    switches: -avz --delete
                    path: dist/
                    remote_path: ${{ secrets.DEPLOY_PATH }}
                    remote_host: ${{ secrets.DEPLOY_HOST }}
                    remote_user: ${{ secrets.DEPLOY_USER }}
                    remote_key: ${{ secrets.DEPLOY_KEY }}
